ALTER SESSION SET CURRENT_SCHEMA=&USUARIOBD;

@@01_TABLAS/INSTALL_TABLAS.sql
@@02_SECUENCIAS/INSTALL_SECUENCIAS.sql
@@03_FUNCIONES/INSTALL_FUNCIONES.sql
@@04_DATOS/INSTALL_DATOS.sql
@@05_FOREIGN_KEY/INSTALL_FOREIGN.sql
@@06_TIPOS/INSTALL_TIPOS.sql
@@10_PAQUETES/INSTALL_PAQUETES.sql


