Prompt 
Prompt Creando FKs en tabla AUT_TPERSN

prompt FK_AUT_TPERSN_GE_TCIUD

ALTER TABLE "&USUARIOBD"."AUT_TPERSN" 
ADD CONSTRAINT "FK_AUT_TPERSN_GE_TCIUD" 
FOREIGN KEY ("PERSN_CIUD")
REFERENCES "&USUARIOBD"."GE_TCIUD" ("CIUD_CIUD") ENABLE;