REM ******************************************************************
REM Fecha         : 01/02/2019
REM Realizado por : Ada
REM Base de Datos : &PROYECTO
REM ******************************************************************

REM TABLESPACE TEMPORAL
Create Temporary tablespace &TS_TEMP TEMPFILE
'&RUTA\&TS_TEMP_FILE' size 300m
         Extent management local uniform size 2m
;

REM TABLESPACE DE DATOS

CREATE TABLESPACE &TS_DEFAULT DATAFILE
'&RUTA\&TS_DEFAULT_FILE' SIZE 300M AUTOEXTEND
ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


REM TABLESPACE DE INDICES

CREATE TABLESPACE &TS_INDICES DATAFILE
'&RUTA\&TS_INDICES_FILE' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
