REM ******************************************************************
REM Fecha         : 01/02/2019
REM Realizado por : Ada
REM Base de Datos : ADA_DB
REM ******************************************************************

--  INSTRUCCIONES:
--  REEMPLAZAR LAS CONSTANTES A CONTINUACION
--  REEMPLAZAR LA CADENA _ADADB_ POR EL NOMBRE DEL PROYECTO
DEFINE USUARIOBD = 'ADA_DB_US';
DEFINE CLAVEBD = 'ada_db_us';
DEFINE TS_DEFAULT = 'TS_D_ADADB_';
DEFINE TS_TEMP = 'TS_T_ADADB_';
DEFINE TS_INDICES = 'TS_I_ADADB_';


REM TABLESPACE Y SEGMENTOS DE ROLLBACK
SET FEEDBACK OFF
SPOOL TMP.LST
SELECT DISTINCT 'pause DEBE estar conectado con Usuario SYSTEM' || CHR(10) || 'ROLL' || CHR(10) || 'EXIT'
FROM DUAL
WHERE USER <> 'SYSTEM'
/
SPOOL OFF
START TMP.LST
SET FEEDBACK ON

REM USUARIO  DUENHO DEL APLICATIVO
DROP USER &USUARIOBD CASCADE;
/

REM TABLESPACE DE DATOS
DROP TABLESPACE &TS_DEFAULT INCLUDING CONTENTS
/

REM TABLESPACE DE INDICES 
DROP TABLESPACE &TS_INDICES INCLUDING CONTENTS
/

REM TABLESPACE TEMPORAL
DROP TABLESPACE &TS_TEMP
/






