/* Create Foreign Key Constraints */

ALTER TABLE  "&USUARIOBD"."GE_TCIUD" 
 ADD CONSTRAINT "FK_GE_TCIUD_GE_TDEPTO"
    FOREIGN KEY ("CIUD_DEPTO") REFERENCES  "&USUARIOBD"."GE_TDEPTO" ("DEPTO_DEPTO")
;